### ISSUE TITLE
Rework app cards

### ISSUE THREAD

**Issue by Markionium** [dhis2/app-management-app#5]
+ Perhaps we can use the icons in some way?
+ Rework the cards partially in accordance to #4 
+ The description seems very "boring"

![image](https://cloud.githubusercontent.com/assets/2134901/12717116/ecfa0f5a-c8e5-11e5-99d8-8f6ebff754f1.png)

**Comment by nicolayr** [comment]
Unfortunately icons aren't available until the app has been installed, so that would require changing the app store.

As for the boringness of the descriptions - the best we can do in that regard in the app management app is to [translate them to pirate](https://www.npmjs.com/package/pirate-speak) ;) But it's probably more productive to spice up the descriptions in the app store.

Some screenshots could be a good start, but with the possible exception of visualisation apps most apps probably won't have much fancy graphics to show off anyway. I suspect we have to live with some boringness.
